[DPE-4279] Revamp Charmed Spark documentation
canonical/spark-k8s-bundle pull request #14
Opened 2024-05-03 22:15 UTC by deusebio

2024-05-05 13:51 UTC, welpaolo approved these changes
Looks really good to me! 
Just left a minor comment

2024-05-06 04:57 UTC, theoctober19th approved these changes
I see there are some issues with line breaks and a few hyperlinks. On overall, it looks good to me.

2024-05-08 08:23 UTC, grobbie requested changes
Quite a few comments, but great work 👍

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-expose-spark-history-server.md
> +If you are running MicroK8s, you can directly expose it to the local network by enabling DNS
I don't think we should explain how to do this. This is super hacky

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-expose-spark-history-server.md
> +The Spark History server can be exposed outside a K8s cluster by means of an ingress. This is the recommended way in production for any K8s distribution. If you are running on MicroK8s, make sure tha
We should provide a generic overview of what they user requires on any platform, and then give a worked example for Microk8s

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-expose-spark-history-server.md
> +If COS is enabled, you can the ingress already provided as part of the COS bundle. Otherwise, you can deploy one using
You can use the ingress

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-history-server-authorization.md
> +the bundles, as described [here](TODO), that includes a Spark History Server charm, already configured with an object storage backend.
Provide link

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-history-server-authorization.md
> +In order to enable authentication, we first need to deploy the [identity bundle](https://discourse.charmhub.io/t/iam-bundle-deployment-tutorial/11916).
Give a short overview of the identity bundle

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-manage-service-accounts.md
> +> **Note** Charmed Spark service accounts are designed to work seamlessly integrated with the Spark Integration Hub charm, allowing you to configure Spark configuration using Juju relations. You can
Seamlessly with the charmed spark integration hub

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-manage-service-accounts.md
> +> **Note** Charmed Spark service accounts are designed to work seamlessly integrated with the Spark Integration Hub charm, allowing you to configure Spark configuration using Juju relations. You can
Manage Spark configuration

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-manage-service-accounts.md
> +> **Note** Charmed Spark service accounts are designed to work seamlessly integrated with the Spark Integration Hub charm, allowing you to configure Spark configuration using Juju relations. You can
Update with link

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-manage-service-accounts.md
> +> :warning: The following commands assume that you have administrative permission on the namespaces (or on the kubernetes cluster) such that the corresponding resources (such as service accounts, sec
So that the corresponding

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +For more information about COS, please refer to [here](https://charmhub.io/topics/canonical-observability-stack).
Again, use meaningful hyperlink text descriptors

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +For more information about Charmed Spark and COS integration, please refer to the explanation section about [monitoring](/todo).
Add link

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +Once COS is correctly setup, to enable monitoring it is necessary to:
The next step is to enable monitoring:

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +The Charmed Spark solution already bundles all the components required for
Required to integrate COS

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +The Charmed Spark solution already bundles all the components required for
As well as to configure the

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +Please refer to the [how-to deploy](/TODO) guide for more information.
Add link

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +The `cos-configuration-k8s` charm included in the bundle can be used to configure
To customise the dashboard

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +the Grafana dashboard. We provide a default dashboard [here](https://github.com/canonical/spark-k8s-bundle/blob/main/releases/3.4/resources/grafana).
Meaningful link text

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +provided to Grafana, thus enabling to version the resources.
Enabling versioning of the resource

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +contents is synced either upon a `update-status` event or after running the action:
The contents are synced intermittently or after

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +You can find more information about the `cos-configuration-k8s` charm [here](https://discourse.charmhub.io/t/cos-configuration-k8s-docs-index/7284).
Meaningful link text

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +In particular, it can be very crucial to configure the scraping interval to make sure
It is crucial

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +is valued correctly. The Prometheus Pushgateway address and port should be can be consistent with what is exposed by Juju, e.g.
Is configured with the correct values

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +via Juju relations, therefore providing a charming user-experience.
Providing an integrated user experience

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +[this](/TODO) how-to guide. Alternatively, you can also deploy the
Add link

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +Spark Integration Hub charm standalone by
By running the following command

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +Once deployed, the Spark Integration Hub will start managing the properties for all the service
Will automatically manage

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +[S3 integrator charm](https://charmhub.io/s3-integrator) to enable integration with an S3 object storage.
An S3 object storage system

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +Once a `s3-integrator` charm is set up, the Spark Integration Hub charm can be related with
Can be integrated with

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +This will add relevant configuration properties to your Charmed Spark service accounts,
Automatically add relevant configuration properties to your spark jobs,

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +that can be verified using the snap, e.g.
Using the tools provided in the spark-client snap

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +where you should see additional configuration automatically added to your service-account
You should see...(Remove "where")

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +> adding configuration already specified via relation will effectively override
Configuration items already provided by the integration will be overridden

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/how-to/h-use-integration-hub.md
> +> them, thus allowing some customization on top of what provided by the relations.
Some customisation of what is automatically configured by the integration

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/reference/r-contacts.md
> +Contact Canonical Data Platform team in [Matrix](https://matrix.to/#/#charmhub-data-platform:ubuntu.com).
Chat with the Canonical Data Platform team on Matrix

2024-05-08 08:23 UTC, grobbie commented on releases/3.4/yaml/docs/reference/r-contacts.md
> +Report your ideas/issues on [GitHub](https://github.com/canonical/spark-k8s-bundle/issues/new).</br>
What about pull requests?

2024-05-23 12:29 UTC, deusebio commented on releases/3.4/yaml/docs/explanation/e-configuration.md
> +Using the different
The settings in my IDE do this by default. I don't see any reason not to, provided that in Markdown, this should not matter. Markdown would not create a new line when you break two lines in the source

2024-05-23 16:45 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-deploy.md
> +| service_account | Service Account to be used by Kyuubi Engines (deprecated)                                                     |
@grobbie I believe it is important. In an "how-to" we need to provide the comprehensive instructions on how a command can be used. For a CLI would be listing all possible arguments. In this case, it would be the arguments that a bundle can be customized with. So, I'll keep this. 

@theoctober19th eventually we should provide the service account to Kyuubi through relation, not via config. So this configuration would not be needed in the mid-term. I will leave it for now, but once we have integration between kyuubi <> integration hub available, then we can remove this.

2024-05-23 17:03 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-deploy.md
> +```python
I have kept Python, but also added `aws-cli` (chose this since we already had tested code for doing this in the CI that I could copy and paste). Of course, we can add more in the future if relevant.

2024-05-23 17:05 UTC, deusebio commented on releases/3.4/yaml/docs/explanation/e-configuration.md
> +configurations, that are merged and overridden based on a precedence rule.
Not really. Natively Spark only allows to read from a single file, there is no merging capabilities. I was a bit surprised when I found this out TBH

2024-05-23 17:06 UTC, deusebio commented on releases/3.4/yaml/docs/explanation/e-configuration.md
> +their lifecycle from creation, modification and deletion. Please refer to [here](/todo)
Yes, once I will consolidate the docs here, I will start creating the discourse topics and add the links here

2024-05-24 08:33 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-deploy.md
> +To see how to setup a Juju controller on K8s and the juju client, you can refer to existing tutorials and documentation, e.g. [here](https://juju.is/docs/olm/get-started-with-juju) for MicroK8s and [
That's fine, but I would believe this would go a bit beyond the scope of the ticket here. I would like to both test microceph and then write that up nicely in the documentation. I have created a dedicated ticket for this, [DPE-4420](https://warthogs.atlassian.net/browse/DPE-4420)

2024-05-24 08:41 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-deploy.md
> +> NOTE: From version XX and on, this should not be necessary as the Spark service account is created automatically by the charms.
This will be available soon. I have commented out the line!

2024-05-24 08:51 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-deploy.md
> +* Terraform modules
naaa. I want to stress that we provide two artifacts, either YAML or TF files, not the tool. Otherwise by analogy, I should refer also to the tool in the "native juju YAML bundles" that is Juju

I have rephrease the opening in 

> Charmed Spark can be deployed **via**

I hope it is fine

2024-05-24 08:57 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-deploy.md
> +* Charmed Spark 3.4.x
-1 

In spark, our channels are "3.4". This is also reflected in the naming of the folders in this repo. When we will support other tracks/channels, we can add other bullet points

2024-05-24 08:58 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-deploy.md
> +After some time, you will see that most of the charms will be in a blocked status because of missing or invalid S3 credentials.
naaa, this reflects the messaging in the status of the charm. I will leave this as is

2024-05-24 08:59 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-deploy.md
> +The Charmed Spark Terraform modules can be configured using a `.tfvars.json` file with the following schema:
Yes, but I would strongly suggest people to store these configs in files. The commands are not fully treacable "as code". Anyhow, if they know a bit of TF, they can infer this easily, but I would not nudge them

2024-05-24 15:27 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-expose-spark-history-server.md
> +If you are running MicroK8s, you can directly expose it to the local network by enabling DNS
We already mention in the docs that the "With ingress" is the recommended way. I believe it is fair to keep this part, if someone does not want to deploy traefik.

2024-05-24 15:34 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-expose-spark-history-server.md
> +The Spark History server can be exposed outside a K8s cluster by means of an ingress. This is the recommended way in production for any K8s distribution. If you are running on MicroK8s, make sure tha
Added text here

2024-05-24 15:35 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-history-server-authorization.md
> +the bundles, as described [here](TODO), that includes a Spark History Server charm, already configured with an object storage backend.
will be added when creating discourse topics

2024-05-24 15:37 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-history-server-authorization.md
> +In order to enable authentication, we first need to deploy the [identity bundle](https://discourse.charmhub.io/t/iam-bundle-deployment-tutorial/11916).
I don't think this is appropriate in a how to, provided we give a link. I believe this is the recommended pattern, to keep how-to, to only really required information to carry out the task

2024-05-24 16:21 UTC, deusebio commented on releases/3.4/yaml/docs/how-to/h-spark-monitoring.md
> +contents is synced either upon a `update-status` event or after running the action:
I prefer to be precise, since people can customize the frequency of the update status, so it is informative for user to have this specific detail

2024-06-03 22:00 UTC, deusebio commented
superseded by #23

2024-06-03 22:00 UTC, closed without merging